import type { BoxShadowPreset } from "./types";

export const boxShadowPresets: BoxShadowPreset[] = [
  {
    id: "soft",
    name: "Soft",
    state: {
      offsetX: 0,
      offsetY: 4,
      blur: 16,
      spread: 0,
      color: "#000000",
      opacity: 0.08,
      inset: false,
    },
  },
  {
    id: "material",
    name: "Material",
    state: {
      offsetX: 0,
      offsetY: 2,
      blur: 4,
      spread: 0,
      color: "#000000",
      opacity: 0.18,
      inset: false,
    },
  },
  {
    id: "neumorphism",
    name: "Neumorphism",
    state: {
      offsetX: 6,
      offsetY: 6,
      blur: 16,
      spread: 0,
      color: "#A3B1C6",
      opacity: 0.45,
      inset: true,
      bgColor: "#E0E5EC",
      objectColor: "#E0E5EC",
    },
  },
  {
    id: "sharp",
    name: "Sharp",
    state: {
      offsetX: 4,
      offsetY: 4,
      blur: 0,
      spread: 0,
      color: "#000000",
      opacity: 0.25,
      inset: false,
    },
  },
  {
    id: "glow",
    name: "Glow",
    state: {
      offsetX: 0,
      offsetY: 0,
      blur: 32,
      spread: 4,
      color: "#6366F1",
      opacity: 0.45,
      inset: false,
    },
  },
  {
    id: "drop",
    name: "Drop",
    state: {
      offsetX: 0,
      offsetY: 12,
      blur: 16,
      spread: 0,
      color: "#000000",
      opacity: 0.2,
      inset: false,
    },
  },
  {
    id: "elevated",
    name: "Elevated",
    state: {
      offsetX: 0,
      offsetY: 20,
      blur: 48,
      spread: 0,
      color: "#000000",
      opacity: 0.22,
      inset: false,
    },
  },
  {
    id: "inner",
    name: "Inner",
    state: {
      offsetX: 0,
      offsetY: 2,
      blur: 8,
      spread: 2,
      color: "#000000",
      opacity: 0.2,
      inset: true,
    },
  },
  {
    id: "outline",
    name: "Outline",
    state: {
      offsetX: 0,
      offsetY: 0,
      blur: 0,
      spread: 3,
      color: "#000000",
      opacity: 0.35,
      inset: false,
    },
  },
  {
    id: "brutalist",
    name: "Brutalist",
    state: {
      offsetX: 8,
      offsetY: 8,
      blur: 0,
      spread: 0,
      color: "#000000",
      opacity: 1,
      inset: false,
    },
  },
];
