import type { GlassmorphismPreset } from "./types";

export const glassmorphismPresets: GlassmorphismPreset[] = [
  {
    id: "light",
    name: "Светлое стекло",
    state: {
      blur: 20,
      opacity: 0.15,
      tintColor: "#FFFFFF",
      highlightColor: "#FFFFFF",
      highlightOpacity: 0.5,
      borderWidth: 1,
      borderColor: "#FFFFFF",
      borderOpacity: 0.3,
      borderRadius: 20,
      shadowDepth: 10,
      highlights: true,
      bgPreset: "gradient",
    },
  },
  {
    id: "dark",
    name: "Тёмное стекло",
    state: {
      blur: 16,
      opacity: 0.2,
      tintColor: "#1A1A2E",
      highlightColor: "#FFFFFF",
      highlightOpacity: 0.15,
      borderWidth: 1,
      borderColor: "#FFFFFF",
      borderOpacity: 0.1,
      borderRadius: 20,
      shadowDepth: 16,
      highlights: true,
      bgPreset: "dark",
    },
  },
  {
    id: "ios",
    name: "iOS",
    state: {
      blur: 12,
      opacity: 0.25,
      tintColor: "#FFFFFF",
      highlightColor: "#FFFFFF",
      highlightOpacity: 0.4,
      borderWidth: 1,
      borderColor: "#FFFFFF",
      borderOpacity: 0.2,
      borderRadius: 16,
      shadowDepth: 8,
      highlights: true,
      bgPreset: "gradient",
    },
  },
  {
    id: "frosted",
    name: "Морозное",
    state: {
      blur: 30,
      opacity: 0.08,
      tintColor: "#FFFFFF",
      highlightColor: "#FFFFFF",
      highlightOpacity: 0.3,
      borderWidth: 1,
      borderColor: "#FFFFFF",
      borderOpacity: 0.25,
      borderRadius: 24,
      shadowDepth: 12,
      highlights: false,
      bgPreset: "image",
    },
  },
  {
    id: "subtle",
    name: "Тонкое",
    state: {
      blur: 8,
      opacity: 0.1,
      tintColor: "#FFFFFF",
      highlightColor: "#FFFFFF",
      highlightOpacity: 0.2,
      borderWidth: 1,
      borderColor: "#FFFFFF",
      borderOpacity: 0.15,
      borderRadius: 12,
      shadowDepth: 6,
      highlights: false,
      bgPreset: "gradient",
    },
  },
  {
    id: "vivid",
    name: "Яркие блики",
    state: {
      blur: 20,
      opacity: 0.12,
      tintColor: "#FFFFFF",
      highlightColor: "#FFFFFF",
      highlightOpacity: 0.8,
      borderWidth: 1,
      borderColor: "#FFFFFF",
      borderOpacity: 0.4,
      borderRadius: 20,
      shadowDepth: 14,
      highlights: true,
      bgPreset: "gradient",
    },
  },
];
